redis:
  endpoint: localhost:6379
  password: null
  minIdle: 0
  maxIdle: 0
  maxTotal: 1
  ssl: false
  timeout: 2000

useInMemoryCache: false

swagger:
  resourcePackage: com.refactorable.resources, com.refactorable.api